import type { ProfileDocument, ProfileStyle } from "@shared/profile-document";

// Development-only regression fixture. The shape mirrors a long senior CV, but
// every person, employer, claim and contact detail below is fictional.
export function visualProfileFixture(style: ProfileStyle = "executive"): ProfileDocument {
  return {
    schemaVersion: 1,
    style,
    identity: {
      name: "Maya Ramanathan",
      title: "Regional Operations & Transformation Leader",
      location: "Singapore",
      headline: "Building dependable regional services across complex markets.",
      summary: "I lead regional service operations and transformation where customer experience, commercial discipline, and change meet. My strongest work turns fragmented ways of working into clear systems that teams can use, leaders can trust, and clients can feel.",
      photoUrl: null,
      videoUrl: null,
      showPhoto: true,
      showVideo: true,
    },
    projects: [
      {
        id: "project-1",
        title: "Building one operating model across six markets",
        company: "Northstar Services",
        summary: "Created a shared operating model while preserving the local decisions each market needed to make.",
        challenge: "Country teams used different handoffs, measures, and escalation paths. Leaders could not see the same risks, and local teams waited too long for regional decisions.",
        contribution: "I mapped the failure points with market leads, agreed a common operating cadence, and gave each team clear decision rights. I tested the model with two markets before the wider rollout.",
        outcome: "Leaders saw risks earlier and teams resolved more work without regional escalation. The shared model became the basis for quarterly planning across the region.",
        sourceIds: ["source-1"],
      },
      {
        id: "project-2",
        title: "Rebuilding a high-friction customer journey",
        company: "Atlas Group",
        summary: "Brought four teams around one customer journey and a simpler ownership model.",
        challenge: "Customers repeated the same information across four teams and could not tell who owned the next step.",
        contribution: "I brought operations, product, and service teams around one journey, removed duplicate checks, and introduced a single named owner for complex cases.",
        outcome: "The new flow reduced avoidable handoffs and gave customers one clear route to resolution.",
        sourceIds: ["source-2"],
      },
      {
        id: "project-3",
        title: "Launching a regional capability programme for frontline leaders",
        company: "Northstar Services",
        summary: "Designed a practical programme that helped new leaders make better service decisions in their first ninety days.",
        challenge: "New leaders were promoted for technical strength but received inconsistent support when they began managing teams and client expectations.",
        contribution: "I worked with experienced managers to turn real cases into short practice sessions, peer coaching, and decision guides that could be used during live work.",
        outcome: "The programme gave leaders a common language for difficult decisions and was adopted by every market in the region.",
        sourceIds: ["source-3"],
      },
      {
        id: "project-4",
        title: "Redesigning commercial reviews for a strategic client portfolio",
        company: "Northstar Services",
        summary: "Reframed account reviews around decisions, risks, and shared client outcomes.",
        challenge: "Account reviews reported activity but did not help regional and country leaders decide where to intervene.",
        contribution: "I replaced the long reporting pack with a concise decision agenda, coached account leads, and connected delivery risks to the client's priorities.",
        outcome: "Reviews became shorter, clearer, and more useful for resolving cross-market issues.",
        sourceIds: ["source-4"],
      },
    ],
    experience: [
      {
        id: "role-1",
        company: "Northstar Services",
        title: "Regional Operations Director, Customer and Commercial Transformation",
        period: "Feb 2021–Present",
        summary: "Lead service operations and transformation across six Asian markets, with accountability for customer experience, operating discipline, and regional change.",
        highlights: [
          "Built a shared operating cadence across country teams while keeping local decision rights clear.",
          "Led a cross-functional redesign of complex customer journeys and service ownership.",
          "Created regional leadership routines that connected delivery risk, client priorities, and commercial decisions.",
          "Sponsored a frontline capability programme adopted across all six markets.",
        ],
        sourceIds: ["source-1", "source-3", "source-4"],
      },
      {
        id: "role-2",
        company: "Northstar Services",
        title: "Director, Service Excellence and Strategic Accounts",
        period: "Oct 2017–Jan 2021",
        summary: "Improved strategic-account governance and regional service quality during a period of expansion.",
        highlights: [
          "Introduced a common review model for a multi-market client portfolio.",
          "Connected market-level service measures to regional improvement priorities.",
        ],
        sourceIds: ["source-4"],
      },
      {
        id: "role-3",
        company: "Northstar Services",
        title: "Associate Director, Regional Programmes",
        period: "Oct 2013–Sep 2017",
        summary: "Designed and delivered regional programmes for service teams and client leaders.",
        highlights: ["Built reusable programme tools from real delivery cases.", "Coached market leads through adoption and local adaptation."],
        sourceIds: ["source-3"],
      },
      { id: "role-4", company: "Northstar Services", title: "Managing Executive", period: "Oct 2012–Mar 2013", highlights: [], sourceIds: [] },
      { id: "role-5", company: "Northstar Services", title: "Senior Executive", period: "Sep 2010–Sep 2012", highlights: [], sourceIds: [] },
      {
        id: "role-6",
        company: "Atlas Group",
        title: "Senior Consultant",
        period: "2006–2010",
        summary: "Worked with service leaders on operating improvements and customer experience.",
        highlights: ["Mapped and simplified a high-friction customer journey across four teams."],
        sourceIds: ["source-2"],
      },
      { id: "role-7", company: "Harbour Learning Centre", title: "English Language Teacher", period: "2004–2005", highlights: [], sourceIds: [] },
    ],
    employerContributions: [{
      id: "employer-contributions-1",
      company: "Northstar Services",
      contributions: [
        "Developed a reusable governance framework for complex regional accounts.",
        "Connected commercial, service, and customer priorities in one regional review rhythm.",
        "Supported market leaders through changes that crossed formal reporting lines.",
      ],
      sourceIds: ["source-5"],
    }],
    skills: [
      "Regional operations", "Service design", "Operating models", "Change leadership",
      "Customer experience", "Strategic accounts", "Programme design", "Commercial governance",
      "Cross-functional leadership", "Leadership development", "Risk management", "Facilitation",
    ],
    contact: {
      email: "maya@example.com",
      linkedin: "https://linkedin.com/in/maya-example",
      website: null,
      showEmail: true,
      showLinkedin: true,
      showWebsite: false,
    },
    publicBotEnabled: false,
    impactStats: [],
    details: {
      education: ["Master of Business Administration · Eastport University", "Bachelor of Social Sciences · Harbour College"],
      certifications: ["Service Design Practitioner", "Organisational Change Leadership"],
      awards: ["Regional Client Partnership Award · 2023"],
      interests: ["Mentoring first-time people leaders", "Community language learning"],
      showEducation: true,
      showCertifications: true,
      showAwards: true,
      showInterests: false,
    },
    privateContext: {
      workingStyle: "I make complex work easier to understand, give teams clear ownership, and stay close enough to delivery to see where the system is failing.",
      careerDirection: "Regional transformation and advisory work where operating design and customer experience meet.",
      voiceNotes: "Direct, thoughtful, practical.",
      questions: [],
      concerns: [],
    },
    sources: [
      { id: "source-1", kind: "resume", label: "Northstar role", excerpt: "Led regional service operations and introduced a shared operating model across six markets." },
      { id: "source-2", kind: "resume", label: "Atlas role", excerpt: "Simplified a customer journey involving four service teams." },
      { id: "source-3", kind: "resume", label: "Leadership programme", excerpt: "Designed a regional capability programme for frontline leaders." },
      { id: "source-4", kind: "resume", label: "Strategic accounts", excerpt: "Redesigned regional reviews for a strategic client portfolio." },
      { id: "source-5", kind: "resume", label: "Northstar selected contributions", excerpt: "Employer-level contributions that were not assigned to one title in the source CV." },
    ],
    skippedQuestionIds: [],
    answeredQuestionIds: [],
    pendingProposal: null,
    undoStack: [],
  };
}
